In [1]:
import numpy as np
import pandas as pd

### 1.Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arraysCreate an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [2]:
Array1 = np.array([3, 5])
Array2 = np.array([2, 5])
print("Original numbers:")
print(Array1)
print(Array2)
print("Comparison - greater")
print(np.greater(Array1, Array2))
print("Comparison - greater_equal")
print(np.greater_equal(Array1, Array2))
print("Comparison - less")
print(np.less(Array1, Array2))
print("Comparison - less_equal")
print(np.less_equal(Array1, Array2))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


### 2. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives 

In [3]:
print(np.zeros(10))
print(np.ones(10))
print(np.ones(10)*5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### 3.write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [4]:
Array = np.array([[20,31],[12,23]])
print("Sum of all elements:",np.sum(Array))
print("Sum of each column:",np.sum(Array, axis=0))
print("Sum of each row:",np.sum(Array, axis=1))

Sum of all elements: 86
Sum of each column: [32 54]
Sum of each row: [51 35]


### 4.Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [5]:
Array1   = np.array([[20,31],[12,23]])
Array2   = np.array([[200,31],[12,233]])
print("Addition of two Array:",Array1 + Array2)
print("Subraction of two Array:",Array1 - Array2)
print("Multipcation of two Array:",Array1 * Array2)
print("Divition of two Array:",Array1 / Array2)

Addition of two Array: [[220  62]
 [ 24 256]]
Subraction of two Array: [[-180    0]
 [   0 -210]]
Multipcation of two Array: [[4000  961]
 [ 144 5359]]
Divition of two Array: [[0.1        1.        ]
 [1.         0.09871245]]


### 5.Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [6]:
Array = np.array([22, 35, 67])
print("sine of the array of angles given in degrees:",np.sin(Array * np.pi / 180.))
print("cosine of the array of angles given in degrees:",np.cos(Array * np.pi / 180.))
print("tangentof the array of angles given in degrees:",np.tan(Array * np.pi / 180.))

sine of the array of angles given in degrees: [0.37460659 0.57357644 0.92050485]
cosine of the array of angles given in degrees: [0.92718385 0.81915204 0.39073113]
tangentof the array of angles given in degrees: [0.40402623 0.70020754 2.35585237]


### 6.Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [7]:
Data_Frame = pd.DataFrame({'name': ['abi','sam','ram','kavi','Ammu'], 'score': [10, 20, 30, 20, 10], 'age': [10, 20, 30, 20, 10]})
Data_Frame

name  score  age
0   abi     10   10
1   sam     20   20
2   ram     30   30
3  kavi     20   20
4  Ammu     10   10

### 7.Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [8]:
Selected_Columns=Data_Frame[['name','score']]
Selected_Columns

name  score
0   abi     10
1   sam     20
2   ram     30
3  kavi     20
4  Ammu     10

### 8.Write a Pandas program to join the two given dataframes along rows and assign all data.

In [9]:
Data_Frame1=pd.DataFrame({'name': ['Vini','Sibi'], 'score': [10, 20], 'age': [10, 20]})
Joined_Dataframe=pd.concat([Data_Frame,Data_Frame1])
Joined_Dataframe

name  score  age
0   abi     10   10
1   sam     20   20
2   ram     30   30
3  kavi     20   20
4  Ammu     10   10
0  Vini     10   10
1  Sibi     20   20

### 9.Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [10]:
Data_Frame2= pd.DataFrame({'city': ['chennai','mum','delhi','hyd','mum']})
Joined_Dataframe1 = pd.concat([Data_Frame,Data_Frame2],sort = False)
print(Joined_Dataframe1.isna().sum())
Joined_Dataframe1.isna()

name     5
score    5
age      5
city     5
dtype: int64


name  score    age   city
0  False  False  False   True
1  False  False  False   True
2  False  False  False   True
3  False  False  False   True
4  False  False  False   True
0   True   True   True  False
1   True   True   True  False
2   True   True   True  False
3   True   True   True  False
4   True   True   True  False

### 10.Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

In [11]:
Data_Series = pd.Series({'Array': np.array([22, 35, 67])})
Data_Series

Array    [22, 35, 67]
dtype: object